-- ============================================================
-- MBBA — STEP 3: Insert quiz (batch 1 of 2: soal 1-25)
-- (Jalankan SETELAH step2_insert_kurikulum.sql)
-- ============================================================

INSERT INTO public.quiz (id, fasal_id, type, order_index, question, options, correct_answer, placeholder, passing_threshold) VALUES

(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'mc', 1, 'Apa arti مُسْتَقِيمٌ?', '[{"key":"A","value":"Luas"},{"key":"B","value":"Berjalan tegak"},{"key":"C","value":"Tinggi"},{"key":"D","value":"Baik"}]', 'B', NULL, 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'mc', 2, 'Manakah kata yang menunjukkan kata benda feminin (muannats)?', '[{"key":"A","value":"الْبَقَرَةُ"},{"key":"B","value":"الْجِلْدُ"},{"key":"C","value":"الضَّبْعُ"},{"key":"D","value":"النَّخْلَةُ"}]', 'D', NULL, 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'mc', 3, 'Kalimat "هَذَا الْجِلْدُ وَاسِعٌ" terdiri dari berapa kata?', '[{"key":"A","value":"3 kata"},{"key":"B","value":"4 kata"},{"key":"C","value":"5 kata"},{"key":"D","value":"2 kata"}]', 'B', NULL, 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'mc', 4, 'Apa fungsi isim isyaroh "هَذَا"?', '[{"key":"A","value":"Menunjuk kata kerja"},{"key":"B","value":"Menunjuk kata benda mudzakkar"},{"key":"C","value":"Menunjuk kata sifat"},{"key":"D","value":"Menunjuk huruf"}]', 'B', NULL, 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'mc', 5, '"طَوِيلَةٌ" adalah kata sifat (shifah) untuk kata...', '[{"key":"A","value":"الْجِلْدُ"},{"key":"B","value":"النَّخْلَةُ"},{"key":"C","value":"الْبَقَرَةُ"},{"key":"D","value":"الضَّبْعُ"}]', 'B', NULL, 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'mc', 6, 'Bentuk feminin dari "وَاسِعٌ" adalah...', '[{"key":"A","value":"وَاسِعَةٌ"},{"key":"B","value":"مُوسِعٌ"},{"key":"C","value":"إِسْعَةٌ"},{"key":"D","value":"وَسِيعٌ"}]', 'A', NULL, 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'mc', 7, 'Mengapa "الْجِلْدُ" mendapat tanwin?', '[{"key":"A","value":"Karena الْجِلْدُ adalah mubtada"},{"key":"B","value":"Karena الْجِلْدُ adalah khobar yang di-nashab-kan"},{"key":"C","value":"Karena الْجِلْدُ adalah isim isyaroh"},{"key":"D","value":"Karena الْجِلْدُ adalah na''t"}]', 'A', NULL, 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'mc', 8, 'Isim Isyaroh untuk mudzakkar terdekat adalah...', '[{"key":"A","value":"هَذِهِ"},{"key":"B","value":"ذَلِكَ"},{"key":"C","value":"هَذَا"},{"key":"D","value":"أُولَئِكَ"}]', 'C', NULL, 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'mc', 9, 'Isim Isyaroh untuk muannats jauh adalah...', '[{"key":"A","value":"هَذَا"},{"key":"B","value":"تِلْكَ"},{"key":"C","value":"ذَاكَ"},{"key":"D","value":"هَذِهِ"}]', 'B', NULL, 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'mc', 10, 'Apa perbedaan antara الضَّبْعُ dan الضَّبْعَةُ?', '[{"key":"A","value":"Tidak ada perbedaan"},{"key":"B","value":"ضبع adalah mudzakkar, ضبعة adalah muannats"},{"key":"C","value":"ضبع adalah muannats, ضبعة adalah mudzakkar"},{"key":"D","value":"Keduanya adalah اسم yang berbeda"}]', 'B', NULL, 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'mc', 11, 'Dalam kalimat "الْبَقَرَةُ مُسْتَقِيمَةٌ", apa fungsi الْبَقَرَةُ?', '[{"key":"A","value":"Khobar"},{"key":"B","value":"Mubtada"},{"key":"C","value":"Maf''ul bih"},{"key":"D","value":"Na''t"}]', 'B', NULL, 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'mc', 12, 'Kata "هَذَا" termasuk dalam kategori...', '[{"key":"A","value":"Isim Ma''rifat"},{"key":"B","value":"Isim Isyaroh"},{"key":"C","value":"Isim Nakirah"},{"key":"D","value":"Isim Alam"}]', 'B', NULL, 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'mc', 13, 'Huruf apa yang membuat "النَّخْلَةُ" menjadi muannats?', '[{"key":"A","value":"Alif"},{"key":"B","value":"Ta marbuthah (ة)"},{"key":"C","value":"Ya"},{"key":"D","value":"Waw"}]', 'B', NULL, 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'mc', 14, 'Apa arti وَاسِعٌ?', '[{"key":"A","value":"Tinggi"},{"key":"B","value":"Luas"},{"key":"C","value":"Baik"},{"key":"D","value":"Berjalan tegak"}]', 'B', NULL, 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'mc', 15, 'Dalam kalimat nominal (jumlah ismiyah), yang berfungsi sebagai subjek disebut...', '[{"key":"A","value":"Khobar"},{"key":"B","value":"Mubtada"},{"key":"C","value":"Fa''il"},{"key":"D","value":"Na''ib Fa''il"}]', 'B', NULL, 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'mc', 16, 'مُسْتَقِيمٌ adalah...', '[{"key":"A","value":"Isim (kata benda)"},{"key":"B","value":"Khobar (predicate)"},{"key":"C","value":"Fi''il (kata kerja)"},{"key":"D","value":"Harf (huruf)"}]', 'B', NULL, 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'mc', 17, 'Isim Isyaroh untuk mudzakkar jauh adalah...', '[{"key":"A","value":"هَذَا"},{"key":"B","value":"ذَاكَ"},{"key":"C","value":"تِلْكَ"},{"key":"D","value":"أُولَئِكَ"}]', 'B', NULL, 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'mc', 18, 'Dalam kalimat "الْبَقَرَةُ مُسْتَقِيمَةٌ", الْبَقَرَةُ adalah...', '[{"key":"A","value":"Khobar"},{"key":"B","value":"Mubtada"},{"key":"C","value":"Maf''ul bih"},{"key":"D","value":"Na''t"}]', 'B', NULL, 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'mc', 19, 'Kata "هَذَا" termasuk kategori...', '[{"key":"A","value":"Isim Ma''rifat"},{"key":"B","value":"Isim Isyaroh"},{"key":"C","value":"Isim Nakirah"},{"key":"D","value":"Isim Alam"}]', 'B', NULL, 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'mc', 20, 'Huruf apa yang membuat "النَّخْلَةُ" menjadi muannats?', '[{"key":"A","value":"Alif (ا)"},{"key":"B","value":"Ta Marbuthah (ة)"},{"key":"C","value":"Ya (ي)"},{"key":"D","value":"Waw (و)"}]', 'B', NULL, 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'mc', 21, 'Dalam kalimat nominal, yang berfungsi sebagai subjek disebut...', '[{"key":"A","value":"Khobar"},{"key":"B","value":"Mubtada"},{"key":"C","value":"Fa''il"},{"key":"D","value":"Na''ib Fa''il"}]', 'B', NULL, 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'mc', 22, 'مُسْتَقِيمٌ adalah khobar. Khobar berfungsi sebagai...', '[{"key":"A","value":"Kata benda (Isim)"},{"key":"B","value":"Kata sifat (Shifah)"},{"key":"C","value":"Predicate / pengenai"},{"key":"D","value":"Kata keterangan (Zarf)"}]', 'C', NULL, 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'mc', 23, 'Isim Isyaroh untuk mudzakkar jauh adalah...', '[{"key":"A","value":"هَذَا"},{"key":"B","value":"ذَاكَ"},{"key":"C","value":"تِلْكَ"},{"key":"D","value":"أُولَئِكَ"}]', 'B', NULL, 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'mc', 24, 'Apa arti طَوِيلَةٌ?', '[{"key":"A","value":"Luas (feminin)"},{"key":"B","value":"Tinggi (feminin)"},{"key":"C","value":"Baik (feminin)"},{"key":"D","value":"Berjalan tegak (feminin)"}]', 'B', NULL, 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'mc', 25, 'Kata "النَّخْلَةُ" mendapat tanwin karena berfungsi sebagai...', '[{"key":"A","value":"Khobar"},{"key":"B","value":"Mubtada"},{"key":"C","value":"Isim isyaroh"},{"key":"D","value":"Na''t"}]', 'A', NULL, 100);

SELECT 'quiz inserted (batch 1): ' || count(*) as result FROM public.quiz;
