-- ============================================================
-- MBBA — STEP 4: Insert quiz (batch 2 of 2: soal 26-50)
-- (Jalankan SETELAH step3_quiz_1_25.sql)
-- ============================================================

INSERT INTO public.quiz (id, fasal_id, type, order_index, question, options, correct_answer, placeholder, passing_threshold) VALUES

(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'mc', 26, 'Dalam jumlah ismiyah, mubtada dan khobar membentuk kalimat yang bernilai...', '[{"key":"A","value":"Perintah (Amr)"},{"key":"B","value":"Pertanyaan (Istifham)"},{"key":"C","value":"Keterangan (Khabariyah)"},{"key":"D","value":"Penafian (Nafi)"}]', 'C', NULL, 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'fill-arab', 27, 'Lengkapkan: هَذَا الضَّبْعُ مُسْتَقِيمٌ (هَذَا=Ini, الضَّبْعُ=singa, مُسْتَقِيمٌ=berjalan tegak)', NULL, 'مُسْتَقِيمٌ', 'ketik jawaban Arab...', 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'fill-arab', 28, 'Lengkapkan: هَذِهِ الْبَقَرَةُ مُسْتَقِيمَةٌ (هَذِهِ=ini, الْبَقَرَةُ=sapi, مُسْتَقِيمَةٌ=berjalan tegak)', NULL, 'مُسْتَقِيمَةٌ', 'ketik jawaban Arab...', 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'fill-arab', 29, 'Lengkapkan: هَذَا الْجِلْدُ ____ (هَذَا=ini, الْجِلْدُ=kulit)', NULL, 'وَاسِعٌ', 'ketik jawaban Arab...', 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'fill-arab', 30, 'Lengkapkan: هَذِهِ النَّخْلَةُ ____ (هَذِهِ=ini, النَّخْلَةُ=pohon kurma)', NULL, 'طَوِيلَةٌ', 'ketik jawaban Arab...', 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'fill-arab', 31, 'Lengkapkan: ____ الْبَقَرَةُ مُسْتَقِيمَةٌ (kata penunjuk untuk muannats dekat)', NULL, 'هَذِهِ', 'ketik jawaban Arab...', 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'fill-arab', 32, 'Lengkapkan kalimat ke-3: هَذَا الضَّبْعُ مُسْتَقِيمٌ. هَذِهِ الْبَقَرَةُ مُسْتَقِيمَةٌ. هَذَا الْجِلْدُ ____. هَذِهِ النَّخْلَةُ طَوِيلَةٌ.', NULL, 'وَاسِعٌ', 'ketik jawaban Arab...', 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'fill-arab', 33, 'Bentuk feminin dari مُسْتَقِيمٌ adalah...', NULL, 'مُسْتَقِيمَةٌ', 'ketik jawaban Arab...', 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'fill-arab', 34, 'Lengkapkan dengan isim isyaroh mudzakkar dekat: ____ الضَّبْعُ مُسْتَقِيمٌ', NULL, 'هَذَا', 'ketik jawaban Arab...', 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'fill-arab', 35, 'Lengkapkan: هَذَا الضَّبْعُ مُسْتَقِيمٌ (ketik kata yang berarti "berjalan tegak")', NULL, 'مُسْتَقِيمٌ', 'ketik jawaban Arab...', 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'fill-latin', 36, 'Terjemahkan ke huruf Latin: النَّخْلَةُ', NULL, 'an-nakhatu', 'ketik latin...', 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'fill-latin', 37, 'Terjemahkan ke huruf Latin: وَاسِعٌ', NULL, 'wasion', 'ketik latin...', 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'fill-latin', 38, 'Terjemahkan ke huruf Latin: مُسْتَقِيمٌ', NULL, 'mustaqimun', 'ketik latin...', 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'fill-latin', 39, 'Terjemahkan ke huruf Latin: طَوِيلَةٌ', NULL, 'thawilatum', 'ketik latin...', 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'fill-latin', 40, 'Terjemahkan ke huruf Latin: الْبَقَرَةُ', NULL, 'al-baqaratu', 'ketik latin...', 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'fill-latin', 41, 'Terjemahkan ke huruf Latin: الضَّبْعُ', NULL, 'adh-dhabu', 'ketik latin...', 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'fill-latin', 42, 'Terjemahkan ke huruf Latin: مُسْتَقِيمٌ', NULL, 'mustaqimun', 'ketik latin...', 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'fill-latin', 43, 'Terjemahkan ke huruf Latin: وَاسِعٌ', NULL, 'wasion', 'ketik latin...', 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'fill-latin', 44, 'Terjemahkan ke huruf Latin: النَّخْلَةُ طَوِيلَةٌ', NULL, 'an-nakhatu thawilatum', 'ketik latin...', 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'fill-latin', 45, 'Terjemahkan ke huruf Latin: هَذَا الْجِلْدُ وَاسِعٌ', NULL, 'hadza al-jildu wasiun', 'ketik latin...', 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'mc', 46, 'Bentuk feminin dari "وَاسِعٌ" adalah...', '[{"key":"A","value":"وَاسِعَةٌ"},{"key":"B","value":"مُوسِعٌ"},{"key":"C","value":"إِسْعَةٌ"},{"key":"D","value":"وَسِيعٌ"}]', 'A', NULL, 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'mc', 47, 'Isim Isyaroh untuk muannats jauh adalah...', '[{"key":"A","value":"هَذَا"},{"key":"B","value":"تِلْكَ"},{"key":"C","value":"ذَاكَ"},{"key":"D","value":"هَذِهِ"}]', 'B', NULL, 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'mc', 48, 'مُسْتَقِيمٌ adalah khobar. Khobar berfungsi sebagai...', '[{"key":"A","value":"Kata benda (Isim)"},{"key":"B","value":"Kata sifat (Shifah)"},{"key":"C","value":"Predicate / pengenai"},{"key":"D","value":"Kata keterangan (Zarf)"}]', 'C', NULL, 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'fill-arab', 49, 'Lengkapkan: هَذَا الضَّبْعُ مُسْتَقِيمٌ (ketik kata Arab yang berarti "berjalan tegak")', NULL, 'مُسْتَقِيمٌ', 'ketik jawaban Arab...', 100),
(gen_random_uuid(), (SELECT id FROM public.fasal WHERE order_index = 1 AND bab_id = (SELECT id FROM public.bab WHERE order_index = 1 AND bagian_id = (SELECT id FROM public.bagian WHERE order_index = 1))), 'fill-latin', 50, 'Terjemahkan ke huruf Latin: الْجِلْدُ وَاسِعٌ', NULL, 'al-jildu wasiun', 'ketik latin...', 100);

-- ============================================================
-- VERIFIKASI AKHIR
-- ============================================================
SELECT 'bagian' as tbl, count(*) as cnt FROM public.bagian
UNION ALL SELECT 'bab', count(*) FROM public.bab
UNION ALL SELECT 'fasal', count(*) FROM public.fasal
UNION ALL SELECT 'quiz', count(*) FROM public.quiz;
